text_encoder:
  # Optional: mld_clip, mld_bert
  target: GraphMotion.models.architectures.clip.TextEncoder
  params:
    finetune: false # if false, model weights are frozen
    last_hidden_state: false # if true, the last hidden state is used as the text embedding
    latent_dim: ${model.latent_dim}
    modelpath: ${model.clip_path}
